### ISSUE TITLE
Clock is randomly delayed

### ISSUE THREAD

**Issue by lucasmaziero** [arduino-libraries/NTPClient#49]
Hello,
I do not understand why the clock is randomly delayed, but the interesting thing is that it delay exactly the time set in the variable "updateInterval" or the function "setUpdateInterval ()", I already did several tests but I can not find this bug.

Anyone have any idea where this problem is?

**Comment by laurentopia** [comment]
variations in network lag between you and the ntp server?

**Comment by jbrown123** [comment]
This is actually a bug in NTPClient::forceUpdate().  Here's what happens.

In NTPClient.cpp on line 68 a request is sent for the time via UDP.
https://github.com/arduino-libraries/NTPClient/blob/020aaf868d53331a6f2909f7f6a475998c527ae4/NTPClient.cpp#L68

Lines 70-78 wait for a response or timeout after 1 second (line 76).
https://github.com/arduino-libraries/NTPClient/blob/020aaf868d53331a6f2909f7f6a475998c527ae4/NTPClient.cpp#L70-L78

What happens in this case is that a request goes out, but the response comes back after the 1 second timeout and is thus not processed by the code in NTPClient. This response sits in the buffer until the NEXT update request.  On the next update, a new request is sent, but the OLD response (still sitting in the buffer) is processed.  This causes the time to be off by whatever the interval is between calls to update (actually to forceUpdate which is called by update).

I verified this bug by making sendNTPPacket() public (altered the header file) and then calling update followed immediately by sendNTPPacket (thus putting an extra response in the queue).  This causes the system to be forever off by whatever the update interval is.

I'm guessing you also would like the fix ...

The fix is to insert the following code BEFORE the request is sent on line 68:

  // flush any existing packets
  while(this->_udp->parsePacket() != 0)
    this->_udp->flush();

This works perfectly for me even with the aforementioned test code in place.  

I'll submit this as a pull request shortly.

**Comment by lucasmaziero** [comment]
@jbrown123 Thank you very much for the contribution.

**Comment by lxrobotics** [comment]
Fixed by https://github.com/arduino-libraries/NTPClient/pull/62 :wink:
