### ISSUE TITLE
random library folder name

### ISSUE THREAD

**Issue by cweinhofer** [arduino-libraries/NTPClient#67]
When I install this library it is located in the libraries folder in a subfolder named "arduino_[random-six-digit-number]" instead of the name of the library like with other libraries. Anyone know what's going on here?

**Comment by lxrobotics** [comment]
@cweinhofer how did you install this library?

**Comment by lxrobotics** [comment]
@cweinhofer since we are currently in a major cleanup of all open issues I'am going to close this issue for now. If you feel that's not justified or your problem still persists, then feel free to reopen it while providing additional information.

You should also try the forum which is more suited for this kind of questions: https://forum.arduino.cc/ .

**Comment by cweinhofer** [comment]
Hi, @lxrobotics Thanks for jumping back in, even on a very old thread.

I installed the library using the Arduino Library Manager.
